# Generated by Django 6.1.2 on 2026-10-06 18:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boleta",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("certificado_id", models.UUIDField(blank=True, null=True)),
                ("folio_sii", models.TextField(blank=True, null=True)),
                (
                    "monto_bruto",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=14, null=True
                    ),
                ),
                (
                    "tasa_retencion",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "monto_retenido",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=14, null=True
                    ),
                ),
                (
                    "monto_liquido",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=14, null=True
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=30, null=True)),
                ("fecha_emision", models.DateTimeField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("modo_retencion", models.IntegerField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("es_test", models.BooleanField(blank=True, null=True)),
                ("respuesta_sii", models.JSONField(blank=True, null=True)),
                ("rut_emisor_cifrado", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "boleta emitida",
                "verbose_name_plural": "boletas emitidas",
                "db_table": "boletas",
                "ordering": ["-fecha_emision"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoletaRecibida",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("periodo", models.DateField()),
                ("folio", models.TextField()),
                ("codigo", models.TextField(blank=True, null=True)),
                ("estado", models.TextField(blank=True, null=True)),
                ("emisor_nombre", models.TextField(blank=True, null=True)),
                ("emisor_rut_cifrado", models.TextField()),
                ("emisor_rut_hash", models.TextField()),
                ("fecha", models.DateField(blank=True, null=True)),
                (
                    "monto_bruto",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=14, null=True
                    ),
                ),
                ("actualizado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "boleta recibida (cache)",
                "verbose_name_plural": "boletas recibidas (cache)",
                "db_table": "boletas_recibidas_cache",
                "ordering": ["-periodo"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CertificadoDigital",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("alias", models.TextField(blank=True, null=True)),
                ("archivo_path", models.TextField(blank=True, null=True)),
                ("fecha_carga", models.DateTimeField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "verbose_name": "certificado digital",
                "verbose_name_plural": "certificados digitales",
                "db_table": "certificados_digitales",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CorreoPendiente",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("destinatario_email", models.TextField()),
                ("asunto", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviando", "Enviando"),
                            ("enviado", "Enviado"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("intentos", models.IntegerField()),
                ("ultimo_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("enviado_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "correo",
                "verbose_name_plural": "correos (bandeja de salida)",
                "db_table": "correos_pendientes",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("nombre", models.TextField()),
                ("rut_cifrado", models.TextField()),
                ("rut_hash", models.TextField()),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "comision_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="comision %"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "db_table": "empresas",
                "ordering": ["nombre"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HistorialBHE",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("tipo_evento", models.CharField(max_length=40)),
                ("detalle", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "evento de boleta",
                "verbose_name_plural": "historial de boletas",
                "db_table": "historial_bhe",
                "ordering": ["-fecha"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("tipo", models.TextField()),
                ("titulo", models.TextField()),
                ("mensaje", models.TextField()),
                ("leida", models.BooleanField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "notificacion",
                "verbose_name_plural": "notificaciones",
                "db_table": "notificaciones",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("nombre_completo", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("emisor", "Emisor"),
                            ("receptor", "Receptor (empresa)"),
                            ("cliente", "Cliente"),
                            ("contador", "Contador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estado", models.TextField(blank=True, null=True)),
                ("rut_cifrado", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios (perfiles)",
                "db_table": "perfiles",
                "ordering": ["nombre_completo"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Receptor",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("nombre", models.TextField()),
                ("email", models.TextField(blank=True, null=True)),
                ("rut_hash", models.TextField(blank=True, null=True)),
                ("rut_cifrado", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "receptor",
                "verbose_name_plural": "receptores",
                "db_table": "receptores",
                "ordering": ["nombre"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SolicitudBHE",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("periodo", models.DateField()),
                ("monto_ventas", models.DecimalField(decimal_places=0, max_digits=14)),
                (
                    "comision_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="comision %"
                    ),
                ),
                (
                    "monto_comision",
                    models.DecimalField(decimal_places=0, max_digits=14),
                ),
                ("monto_a_pagar", models.DecimalField(decimal_places=0, max_digits=14)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("emitida", "Emitida"),
                            ("anulada", "Anulada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "solicitud de BHE",
                "verbose_name_plural": "solicitudes de BHE",
                "db_table": "solicitudes_bhe",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "periodo",
                    models.DateField(
                        help_text="Siempre el dia 1 del mes (ej. 01-09-2026 = septiembre)"
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=0, max_digits=14)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "venta",
                "verbose_name_plural": "ventas",
                "db_table": "ventas",
                "ordering": ["-periodo"],
                "managed": False,
            },
        ),
    ]
